### ISSUE TITLE
install-dsptoolkit: last command fails: Operation not permitted

### ISSUE THREAD

**Issue by PauLL54** [hifiberry/hifiberry-dsp#16]
install-dsptoolkit fails with message:
mv: failed to preserve ownership for '/boot/config.txt': Operation not permitted

The last line is:
sudo mv /tmp/config.txt /boot/config.txt

**Comment by hifiberry** [comment]
It doesn't fail. It simply can't set permissions as a FAT file system doesn't support these. That's fine.

**Comment by PauLL54** [comment]
It would be nice if the script would show a message that you can ignore this error.
If I see a message like this, I am very alarmed.
A friend of mine also spend some time on this issue.
