### ISSUE TITLE
dspdac-noautomute.xml profile produces an offset voltage of 1V

### ISSUE THREAD

**Issue by PauLL54** [hifiberry/hifiberry-dsp#19]
The dspdac-noautomute.xml profile produces an offset voltage of 1V,
This is a problem if you have a DC coupled amplifier.
Could you please modify this profile (I tried myself, but after that I was not able to use filters).

**Comment by hifiberry** [comment]
We don't work on this profile anymore. The profile is provided as-is. There won't be any further updated from us on this profile.

**Comment by PauLL54** [comment]
Could you please give me a link to the SigmaStudio projects of dspdac-noautomute.xml and dacdsp-default.xml?
Then I could try to improve these profiles myself.
