### ISSUE TITLE
Github CI actions failing

### ISSUE THREAD

**Issue by ssalonen** [hifiberry/hifiberry-dsp#29]
I can see that github actions are failing.

Specifically, flake8 check fails with https://github.com/hifiberry/hifiberry-dsp/runs/1912147490?check_suite_focus=true#step:5:27 (undefined constant ZEROCONF_TYPE)

Is this remnant of zeroconf that was supposedly removed in https://github.com/hifiberry/hifiberry-dsp/commit/768afc51f5330a965f64bfaa880209ec8657968a#diff-a13c2daf6c34cd6530330c6d73a1349eb59a1f44466be15e4f6de84754d7ea45?

**Comment by thomasschalch** [comment]
tried to fix that in #32

**Comment by ssalonen** [comment]
Seems to work! https://github.com/hifiberry/hifiberry-dsp/actions/runs/763297397

Closing!
