### ISSUE TITLE
[Question] What it would take to support other boards

### ISSUE THREAD

**Issue by michalkalinowski-** [hifiberry/hifiberry-dsp#4]
Hello,

I've been looking at beocreate board and in the process I stumbled upon this repo. I love what you did here to skip USBi and program AD's DACs directly.

This gives me an idea to fork / extend your repo to support other SigmaDSPs processors (maybe even SHARC range?). 

From having a brief look at the code it seems you created a class with adau145x config. Am I right thinking that supporting for example ADAU1701 would be just a matter of creating another class with appropriate configuration or am I overlooking something?

To be clear I'm willing to do the work and open a PR :)

Thanks!

**Comment by hifiberry** [comment]
In general it is possible to extend this to other DSPs. There might be some code that might need some rework, just adding a new ADAUxxxx class might not be enough, as there might still be some DSP specific stuff hardcoded in other classes.
