### ISSUE TITLE
No sound from hifiberry

### ISSUE THREAD

**Issue by Llywelyn71** [hifiberry/hifiberry-dsp#5]
Hi all,

I am very new to using a Raspberry Pi and have virtually no knowledge of programming.

I have successfully installed Jriver and am using it to play music via the Hifiberry digi pro + to my DAC. I would like to use Spotify on it too.

So I have downloaded raspotify and it is recognised as another device from my phone etc. That's a good start. I have read about selecting the Hifiberry as a device but I don't understand what I have to do. It mentions changing things in the config files but I don't know how to access these.
The OS I am using is Raspian
Can someone please talk me though how to do this, from the very basics?
Thanks 
Dan

**Comment by hifiberry** [comment]
This has nothing to do with DSP toolkit. You might check here:
https://support.hifiberry.com/hc/en-us

Note that if you're not a Linux system administrator, it is usually the best to use a pre-configured system and NOT trying to set up your own system.
