### ISSUE TITLE
No releases in years?

### ISSUE THREAD

**Issue by ssalonen** [hifiberry/hifiberry-dsp#52]
Why there is no new release for PyPi and in github?

The version in PyPi/github is 0.20 some 2y ago (Dec 24, 2020). Nevertheless, there's many fixes and improvements done in the repo since then.

Is there a reason why no new releases are made?

**Comment by hifiberry** [comment]
Thank you for the PRs. These have been merge, we'll prepare a new PyPi release asap.

**Comment by ssalonen** [comment]
Thanks @hifiberry . Would be perhaps good to tag the release here and/or create github release?
