### ISSUE TITLE
Buggy install-dsptoolkit script 

### ISSUE THREAD

**Issue by adamf663** [hifiberry/hifiberry-dsp#58]
1) sudo apt-get install gcc-aarch64-linux-gnu needs to be added.  
2) reboot needed after running the script, otherwise sigmateltcp dies trying to open spi

**Comment by vincss** [comment]
Hi, 
I also  installed gcc because pyalsaaudio wouldn't install.

**Comment by bkosick** [comment]
FYI on RPi OS Lite, I had to do this to fix the installer
sudo -H pip3 install pyalsaaudio --break-system-packages
