### ISSUE TITLE
ADAU15xx Reported by get_meta

### ISSUE THREAD

**Issue by rawdlite** [hifiberry/hifiberry-dsp#68]
https://github.com/hifiberry/hifiberry-dsp/blob/3384c0cd26088a1c784942c9e23f1f5ca3cd25fb/hifiberrydsp/server/sigmatcp.py#L924

ADAU14XX is written in logging, yet ADAU15xx is returned by get_meta.
Am I supposing correctly this is a typo?

**Comment by hifiberry** [comment]
Fixed in https://github.com/hifiberry/hifiberry-dsp/commit/c555c650749d4eb60d44d9df46629f40dcb66709
